### ISSUE TITLE
Browser UI disruption during audio playback

### ISSUE THREAD

**Issue by Gittyperson** [Gnat008/nosquint#7]
During web playback of audio streams, media controls disappear and web player is not displayed correctly. NoSquint also seems to disable itself. Confirmed on Windows 10 (also on Pale Moon 28.0.0a4), not on Linux.

Examples:

http://www.amigaremix.com/
http://streams.greenhost.nl:8080/oudemuziek

As reported here, with screenshots: https://forum.palemoon.org/viewtopic.php?f=46&t=19382

**Comment by Gittyperson** [comment]
Adding Exceptions in NoSquint's Global Settings doesn't seem to make a difference.

**Comment by Gnat008** [comment]
With NoSquint installed, these errors pop up in the console: http://prntscr.com/jtqdb4
With NS disabled, the errors do not appear, and the controls appear normally.

**Comment by Gnat008** [comment]
Okay, some good news. Using the latest dev build, this issue is already half fixed. Everything works as normal. The only oddity is that the statusbar still shows "N/A" and it doesn't show it as a site. Therefore, I am not sure if this should be closed as fixed or not...

Thoughts?

**Comment by Gnat008** [comment]
Fixed by https://github.com/Gnat008/nosquint/commit/4398233d94b481f77703807c9f6c2c0d371b5cd0

**Comment by Gittyperson** [comment]
I guess you could open another issue for the remaining problem (if you are after perfectionism!) but the main issue is gone. Perhaps the lack of text somehow confuses NoSquint?
